#!/bin/sh
#
# Script to create a note file for 'today'

# TODAY=$(date +"%Y%m%d%H%M%S")
TODAY=$(date +"%Y%m%d")
NAME=$TODAY
DIR=$HOME/Desktop

function die() {
     echo $*
     exit 1
}

if [ $# -eq 1 ]
then
    NAME="$NAME-$1"
fi

FILE="$DIR/$NAME.txt"

if [ -f "$FILE" ]
then
    die "File [$FILE] already exists"
fi

echo "Creating note file $FILE"
touch "$FILE"
