#!/bin/sh

APP=$1
TOMCAT=$2
WEBAPP=$CATALINA_HOME/webapps/$APP
STASH=$CATALINA_HOME/webappsoff/$APP
WAR=$CATALINA_HOME/webapps/$APP.war

function die() {
     echo $*
     exit 1
}

if [ $# -lt 1 ] 
then
	die 'You must specify an app name'
fi	

if [ "$TOMCAT" == 'Y' ] || [ "$TOMCAT" == 'y' ]
then
	echo 'Stopping tomcat'
	tomcat stop
fi

if [ -d $WEBAPP ]
then
	echo "$APP exists in tomcat, moving out..."
	
	if [ -d $STASH ]
	then	
		echo "$APP exists in stash, deleting..."	
		rm -rf $STASH
	fi
	
	mv $WEBAPP $STASH
else
	die "$APP doesn't exist in tomcat, exiting..."
fi
	
if [ -f $WAR ]
then
	echo "$APP war file exists in tomcat, deleting..."
	rm -f $WAR
fi	
