#!/bin/sh
# This deals with starting and stopping tomcat on a unix based system
# Options: start
#                  stop
#                  restart      
#                  kill
#                  tail

function die() {
     echo $*
     exit 1
}

if [ $# -ne 1 ]
then
    die "$0 Specify action"
fi

if [ ! -d $CATALINA_HOME ]
then
    die "Directory $CATALINA_HOME does not exist"
fi

ACTION=$1
echo "Using CATALINA_HOME $CATALINA_HOME"
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export JRE_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home

if [ "$ACTION" == "START" ] || [ "$ACTION" == "start" ] 
then
	echo "Starting tomcat..."
	export JAVA_OPTS="-server -Xms768M -Xmx2048M -XX:MaxPermSize=1024m"
	$CATALINA_HOME/bin/startup.sh
elif [ "$ACTION" == "STOP" ] || [ "$ACTION" == "stop" ] 	
then
	echo "Stopping tomcat..."
	$CATALINA_HOME/bin/shutdown.sh
	# TODO get pid accurately
	# sleep 1
	# ISIT=`pidof $CATALINA_HOME`
	# if [ "$ISIT" != "" ]
	# then
	# 	echo "Tomcat still running - killing process ($ISIT)" 
	# 	tomcat $CATALINA_HOME kill
	# fi    
elif [ "$ACTION" == "KILL" ] || [ "$ACTION" == "kill" ]         
then
	echo 'Killing tomcat...'
	# kill -9 `pidof $CATALINA_HOME`
elif [ "$ACTION" == "RESTART" ] || [ "$ACTION" == "restart" ]   
then
	echo 'Restarting tomcat...'
	tomcat $CATALINA_HOME stop
	tomcat $CATALINA_HOME start
elif [ "$ACTION" == "PID" ] || [ "$ACTION" == "pid" ]         
then
	pidof $CATALINA_HOME
elif [ "$ACTION" == "CLEAN" ] || [ "$ACTION" == "clean" ]       
then
	echo 'Cleaning logs...'
	rm $CATALINA_HOME/logs/*
	# rm -rf $CATALINA_HOME/webapps/*	
elif [ "$ACTION" == "TAIL" ] || [ "$ACTION" == "tail" ]         
then
	echo 'Tailing logs...'
	tail -f $CATALINA_HOME/logs/catalina.out
else
	echo "Unknown action ($ACTION) - Doing nothing"
fi
